#!/usr/bin/env python3
"""Build backend/src/seeds/questions.data.json.

Authors 8 questions per concept per difficulty tier across every tier, with a
spread of difficulty_score within each tier so the adaptive selector has room
to match a learner's running ability. Validates structure on the way out.
"""
import json
import os

# A spread of difficulty_score within each tier (8 distinct values), so
# selectQuestion() can match the learner's ability rather than always returning
# the same item.
BANDS = {
    "basic":        [0.15, 0.18, 0.20, 0.22, 0.25, 0.28, 0.30, 0.33],
    "intermediate": [0.42, 0.46, 0.50, 0.53, 0.56, 0.59, 0.62, 0.65],
    "advanced":     [0.72, 0.76, 0.79, 0.82, 0.85, 0.88, 0.90, 0.93],
}
TIERS = ("basic", "intermediate", "advanced")

# DATA[technology][concept][tier] = list of (text, (opt,opt,opt,opt), correct_index)
DATA = {}


def build(out_path):
    out, seen = [], set()
    for tech, concepts in DATA.items():
        for concept, tiers in concepts.items():
            for tier in TIERS:
                items = tiers.get(tier, [])
                assert len(items) >= 8, f"{tech}/{concept}/{tier}: only {len(items)} (<8)"
                for i, (text, options, ci) in enumerate(items):
                    assert len(options) == 4, f"need 4 options: {text!r}"
                    assert 0 <= ci <= 3, f"correct_index out of range: {text!r}"
                    assert text not in seen, f"duplicate text: {text!r}"
                    seen.add(text)
                    score = BANDS[tier][i] if i < len(BANDS[tier]) else BANDS[tier][-1]
                    out.append({
                        "technology": tech,
                        "concept": concept,
                        "difficulty": tier,
                        "difficulty_score": score,
                        "text": text,
                        "options": list(options),
                        "correct_index": ci,
                        "source": "manual",
                        "status": "active",
                        "metadata": {"prompt_version": "v1", "model": "manual"},
                    })
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {len(out)} questions -> {out_path}")

DATA["javascript"] = {
    "closures": {
        "basic": [
            ("What does a closure give a function access to?",
             ("The variables in its own scope plus those of enclosing scopes and globals",
              "Only its own local variables", "Only global variables", "Only its arguments"), 0),
            ("When is a closure created in JavaScript?",
             ("Whenever a function is defined inside another scope and keeps using its variables",
              "Only when the class keyword is used", "Only inside loops", "Only when a function runs twice"), 0),
            ("A function that 'remembers' variables from where it was defined is called a:",
             ("Closure", "Callback", "Promise", "Generator"), 0),
            ("Closures rely on which kind of scoping in JavaScript?",
             ("Lexical (static) scoping", "Dynamic scoping", "Block-only scoping", "No scoping at all"), 0),
            ("A common practical use of closures is:",
             ("Keeping data private and persisting state between calls",
              "Speeding up the event loop", "Declaring global variables", "Disabling garbage collection"), 0),
            ("In function outer(){ let x = 1; return function(){ return x; }; }, the inner function closes over:",
             ("x", "the global object", "nothing", "the return keyword"), 0),
            ("After the outer function returns, a variable captured by a closure is:",
             ("Still accessible to the inner function", "Immediately deleted",
              "Reset to undefined", "Promoted to a global"), 0),
            ("Which variables can a closure capture from an enclosing function?",
             ("Those declared with let, const, or var", "Only var", "Only const", "None of them"), 0),
        ],
        "intermediate": [
            ("What does for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i)); } log?",
             ("3 3 3", "0 1 2", "0 0 0", "1 2 3"), 0),
            ("Switching to for (let i = 0; i < 3; i++) { setTimeout(() => console.log(i)); } logs:",
             ("0 1 2", "3 3 3", "undefined three times", "a ReferenceError"), 0),
            ("function makeCounter(){ let c = 0; return () => ++c; } const f = makeCounter(); f(); f(); The next f() returns:",
             ("3", "1", "0", "undefined"), 0),
            ("Calling a counter factory twice produces counters that:",
             ("Each keep independent state", "Share one state", "Throw an error", "Always return 0"), 0),
            ("Which pattern uses a closure to emulate private variables?",
             ("An IIFE/module that returns an object exposing only some functions",
              "Using a private keyword", "Declaring vars at top level", "Calling JSON.stringify"), 0),
            ("const fns = []; for (let i = 0; i < 3; i++) fns.push(() => i); fns[1]() returns:",
             ("1", "3", "0", "2"), 0),
            ("Why can closures contribute to memory leaks?",
             ("They keep referenced variables alive, preventing garbage collection",
              "They duplicate the global object", "They turn off the collector", "They run on another thread"), 0),
            ("In function once(fn){ let called=false; return (...a)=>{ if(!called){ called=true; return fn(...a);} }; }, the captured called is:",
             ("Private to each returned function from a single once() call", "Shared globally",
              "Reset on every call", "Always true"), 0),
        ],
        "advanced": [
            ("Using var, how do you capture each loop value in a setTimeout without let?",
             ("Wrap the body in an IIFE that takes i as a parameter",
              "Use const inside the callback", "Call the callback synchronously", "Use a global variable"), 0),
            ("Variables captured by a closure are held by:",
             ("Reference to the variable binding, not a snapshot of its value",
              "A value copy taken at creation", "A deep clone", "A WeakRef only"), 0),
            ("const add = a => b => a + b; const add5 = add(5); add5(3) evaluates to:",
             ("8", "5", "3", "53"), 0),
            ("function memoize(fn){ const cache={}; return n => cache[n] ?? (cache[n]=fn(n)); } The closure preserves:",
             ("The cache object across calls", "Nothing across calls", "Only the last argument", "The function name"), 0),
            ("Which statement about closures and this is correct?",
             ("Closures do not capture this; arrow functions inherit this lexically instead",
              "Closures always capture this", "this is the only thing closures capture", "Closures rebind this to the global object"), 0),
            ("function trap(){ const big = new Array(1e6); return () => big[0]; } Returning the inner function:",
             ("Keeps the large array reachable through the closure", "Frees the array immediately",
              "Copies only big[0]", "Throws a RangeError"), 0),
            ("How do you give an object truly private methods using closures?",
             ("Define them inside a factory and expose only chosen members on the returned object",
              "Prefix names with an underscore", "Call Object.freeze", "Declare them with var"), 0),
            ("Each invocation of an outer function creates:",
             ("A new closure environment with its own captured bindings",
              "One scope shared by all invocations", "A copy of only the global scope", "No new scope"), 0),
        ],
    },
    "promises": {
        "basic": [
            ("What does a Promise represent?",
             ("The eventual result of an asynchronous operation", "A synchronous return value",
              "A type of loop", "A CSS animation"), 0),
            ("What are the three states of a Promise?",
             ("pending, fulfilled, rejected", "open, closed, error",
              "start, run, stop", "new, used, done"), 0),
            ("Which method handles a fulfilled Promise's value?",
             (".then()", ".catch()", ".finally()", ".throw()"), 0),
            ("Which method handles a rejected Promise?",
             (".catch()", ".then()", ".resolve()", ".await()"), 0),
            ("What does Promise.resolve(42) return?",
             ("A Promise already fulfilled with 42", "The number 42 directly",
              "A rejected Promise", "undefined"), 0),
            ("The keyword used to pause an async function until a Promise settles is:",
             ("await", "yield", "defer", "hold"), 0),
            ("An async function always returns:",
             ("A Promise", "undefined", "the awaited value synchronously", "a callback"), 0),
            (".finally() on a Promise runs:",
             ("Whether the Promise fulfills or rejects", "Only on fulfillment",
              "Only on rejection", "Never"), 0),
        ],
        "intermediate": [
            ("Promise.all([p1, p2]) rejects when:",
             ("Any one of its promises rejects", "All of its promises reject",
              "The first one fulfills", "Never"), 0),
            ("Promise.race([p1, p2]) settles with:",
             ("The first promise to settle (fulfill or reject)", "The last promise to settle",
              "All results in an array", "Only fulfilled results"), 0),
            ("What does Promise.allSettled return?",
             ("A promise that fulfills with an array describing each outcome",
              "A promise that rejects on first failure", "The first fulfilled value", "undefined"), 0),
            ("Inside an async function, try/catch can catch errors from:",
             ("awaited promises that reject", "only synchronous throws",
              "only network errors", "nothing"), 0),
            ("What is the result of await Promise.reject(new Error('x')) without a try/catch?",
             ("It throws, rejecting the surrounding async function", "It returns the Error object",
              "It returns undefined", "It is ignored"), 0),
            ("Returning a promise inside a .then() callback causes the chain to:",
             ("Wait for that promise before continuing", "Ignore the returned promise",
              "Reject immediately", "Run the next then synchronously"), 0),
            ("Promise.any([p1, p2]) fulfills with:",
             ("The first fulfilled value, rejecting only if all reject",
              "The first rejection", "All values", "the last value"), 0),
            ("Which best avoids 'callback hell'?",
             ("Chaining .then() or using async/await", "Nesting more callbacks",
              "Using setTimeout", "Using only synchronous code"), 0),
        ],
        "advanced": [
            ("const r = [1,2,3].map(async x => x*2); What is r?",
             ("An array of pending promises", "An array [2,4,6]",
              "A single promise of [2,4,6]", "undefined"), 0),
            ("To run async work over an array sequentially you should:",
             ("await inside a for...of loop", "use array.map with await",
              "use Promise.all", "use forEach with await"), 0),
            ("A rejected promise with no rejection handler triggers:",
             ("An unhandledrejection event", "A syntax error",
              "A silent success", "An immediate process exit by spec"), 0),
            ("await blocks only:",
             ("The current async function, not the whole thread",
              "The entire event loop", "all timers", "the microtask queue permanently"), 0),
            ("Promise callbacks (.then) are scheduled on the:",
             ("Microtask queue", "Macrotask queue", "Call stack directly", "Render queue"), 0),
            ("Promise.all preserves results in:",
             ("Input order, regardless of which settles first",
              "Completion order", "Reverse order", "Random order"), 0),
            ("Wrapping a callback API in a promise is called:",
             ("Promisification", "Currying", "Memoization", "Debouncing"), 0),
            ("new Promise(executor) runs its executor function:",
             ("Synchronously, at construction time", "On the next microtask",
              "After a 0ms timeout", "Only when .then is attached"), 0),
        ],
    },
    "event-loop": {
        "basic": [
            ("JavaScript executes user code on:",
             ("A single main thread", "Multiple threads by default",
              "The GPU", "No thread"), 0),
            ("The event loop's job is to:",
             ("Move queued callbacks onto the call stack when it is empty",
              "Compile the code", "Allocate memory", "Render CSS"), 0),
            ("setTimeout(fn, 0) schedules fn to run:",
             ("After the current synchronous code finishes", "Immediately, before other code",
              "Never", "On a separate thread"), 0),
            ("The call stack holds:",
             ("The functions currently executing", "Pending timers",
              "Network responses", "DOM nodes"), 0),
            ("Long synchronous work on the main thread will:",
             ("Block rendering and other callbacks", "Run in parallel automatically",
              "Be moved to a worker", "Be skipped"), 0),
            ("Which queue do setTimeout callbacks go to?",
             ("The macrotask (task) queue", "The microtask queue",
              "The call stack", "The render queue"), 0),
            ("Which queue do Promise .then callbacks go to?",
             ("The microtask queue", "The macrotask queue",
              "The call stack", "The timer queue"), 0),
            ("Web APIs like setTimeout and fetch are provided by:",
             ("The host environment (browser/Node), not the JS engine itself",
              "The V8 engine core", "The microtask queue", "The call stack"), 0),
        ],
        "intermediate": [
            ("console.log(1); setTimeout(()=>console.log(2)); Promise.resolve().then(()=>console.log(3)); console.log(4); prints:",
             ("1 4 3 2", "1 2 3 4", "1 4 2 3", "1 3 4 2"), 0),
            ("Microtasks are drained:",
             ("Completely before the next macrotask runs", "After all macrotasks",
              "Only once per second", "Never automatically"), 0),
            ("A promise chain that keeps queuing microtasks can:",
             ("Starve macrotasks/rendering until it finishes", "Speed up timers",
              "Run on another thread", "Be ignored by the loop"), 0),
            ("queueMicrotask(fn) schedules fn:",
             ("On the microtask queue, before the next macrotask", "On the macrotask queue",
              "Synchronously now", "After 4ms"), 0),
            ("In browsers, setTimeout's minimum delay for nested timers is clamped to roughly:",
             ("4ms", "0ms always", "100ms", "1s"), 0),
            ("await effectively schedules the continuation as:",
             ("A microtask after the awaited value settles", "A macrotask",
              "Synchronous code", "An animation frame"), 0),
            ("requestAnimationFrame callbacks run:",
             ("Before the next repaint", "After all timers for the session",
              "On the microtask queue", "Only once ever"), 0),
            ("Two setTimeout(fn, 0) calls execute their callbacks:",
             ("In the order they were scheduled, one task each", "Simultaneously",
              "In reverse order", "As microtasks"), 0),
        ],
        "advanced": [
            ("In Node.js, process.nextTick callbacks run:",
             ("Before other microtasks (Promise jobs) in the same phase",
              "After all timers", "On the macrotask queue", "Only on exit"), 0),
            ("The Node.js event loop is organized into:",
             ("Phases such as timers, poll, check, and close callbacks",
              "A single FIFO queue only", "Two threads", "No structure"), 0),
            ("setImmediate(fn) vs setTimeout(fn,0) inside an I/O callback in Node:",
             ("setImmediate generally runs first (check phase before next timers)",
              "setTimeout always runs first", "They never differ", "Both are microtasks"), 0),
            ("Recursively scheduling process.nextTick can:",
             ("Starve the event loop, blocking I/O", "Speed up I/O",
              "Run on a worker thread", "Be merged by Node"), 0),
            ("Microtasks scheduled inside a microtask are processed:",
             ("In the same drain, before returning to macrotasks", "On the next macrotask",
              "After 4ms", "Never"), 0),
            ("Which correctly orders these by priority after sync code in the browser?",
             ("Microtasks, then a macrotask, then rendering", "Rendering, then microtasks, then macrotasks",
              "Macrotasks, then microtasks", "They are unordered"), 0),
            ("CPU-bound work that must not block the UI thread should run in:",
             ("A Web Worker (or worker_threads in Node)", "A setTimeout(0)",
              "A microtask", "requestAnimationFrame"), 0),
            ("An async function that only awaits already-resolved promises still:",
             ("Yields to the microtask queue at each await", "Runs fully synchronously",
              "Blocks all timers", "Spawns a thread"), 0),
        ],
    },
}

DATA["react"] = {
    "hooks": {
        "basic": [
            ("What does the useState hook return?",
             ("An array with the current value and a setter function", "Just the current value",
              "A single setter function", "A promise"), 0),
            ("Which hook lets you run side effects in a function component?",
             ("useEffect", "useState", "useMemo", "useRef"), 0),
            ("React Hooks can be called:",
             ("Only at the top level of a component or another hook", "Inside loops and conditions freely",
              "Only inside class methods", "Anywhere, including event handlers conditionally"), 0),
            ("Custom hook names should start with:",
             ("use", "with", "hook", "on"), 0),
            ("Hooks were introduced so that:",
             ("Function components could use state and lifecycle features", "Classes would render faster",
              "JSX could be removed", "Props would be optional"), 0),
            ("useState(0) initializes the state to:",
             ("0", "null", "undefined", "an empty array"), 0),
            ("To read the previous value when updating state you should pass the setter:",
             ("A function of the previous state", "The new value directly only",
              "A promise", "the JSX element"), 0),
            ("Which hook returns a mutable ref object that persists across renders?",
             ("useRef", "useState", "useEffect", "useReducer"), 0),
        ],
        "intermediate": [
            ("An empty dependency array [] in useEffect means the effect runs:",
             ("Once after the first render (and cleanup on unmount)", "After every render",
              "Never", "Only on unmount"), 0),
            ("Omitting the dependency array entirely in useEffect causes it to run:",
             ("After every render", "Only once", "Never", "Only on mount"), 0),
            ("The function returned from a useEffect callback is used to:",
             ("Clean up the effect (e.g., remove listeners) before re-run/unmount",
              "Return JSX", "Set state synchronously", "Memoize a value"), 0),
            ("useMemo is primarily used to:",
             ("Cache an expensive computed value between renders",
              "Run side effects", "Replace useState", "Force a re-render"), 0),
            ("useCallback returns:",
             ("A memoized version of a callback that changes only when deps change",
              "A memoized value", "A ref", "A new component"), 0),
            ("Calling a state setter with the same value as the current state:",
             ("May let React bail out of re-rendering", "Always forces a re-render",
              "Throws an error", "Clears all state"), 0),
            ("Two useState calls in one component:",
             ("Maintain independent, ordered state slots", "Share one state value",
              "Are not allowed", "Must be combined into one"), 0),
            ("useReducer is a good choice when:",
             ("State logic is complex or the next state depends on the previous",
              "You only toggle a boolean", "You never update state", "You need a ref"), 0),
        ],
        "advanced": [
            ("Why must hooks not be called conditionally?",
             ("React relies on a stable call order to associate state across renders",
              "It would slow rendering", "Conditions are not supported in JS", "Hooks need a class"), 0),
            ("A stale closure bug in useEffect usually comes from:",
             ("Omitting a changing value from the dependency array", "Listing too many dependencies",
              "Returning JSX from the effect", "Using useRef"), 0),
            ("useLayoutEffect differs from useEffect in that it runs:",
             ("Synchronously after DOM mutations, before the browser paints",
              "After paint, asynchronously", "Only on the server", "Never on the client"), 0),
            ("To keep a value across renders without triggering re-renders, use:",
             ("useRef", "useState", "useMemo", "useEffect"), 0),
            ("Passing a new inline object as a memoized child's prop each render:",
             ("Breaks memoization because the reference changes", "Has no effect on memoization",
              "Throws a warning", "Freezes the component"), 0),
            ("A custom hook shares logic between components but:",
             ("Each component gets its own isolated state from it", "All components share one state",
              "It must return JSX", "It can only be used once per app"), 0),
            ("React 18 may call a component's render and certain effects twice in development because of:",
             ("Strict Mode double-invocation to surface side-effect bugs", "A memory leak",
              "Concurrent rendering errors", "A deprecated API"), 0),
            ("The functional updater form setX(prev => prev + 1) is preferred when:",
             ("Multiple updates may batch and you need the latest value",
              "You never read previous state", "The value is a constant", "You want to skip a render"), 0),
        ],
    },
    "state": {
        "basic": [
            ("In React, state is:",
             ("Data managed within a component that can change over time",
              "Always passed from the parent and read-only", "Stored only in the DOM", "A CSS property"), 0),
            ("Updating state in React should be done by:",
             ("Calling the state setter, never mutating state directly",
              "Reassigning the variable directly", "Editing the DOM", "Using a global variable"), 0),
            ("When state changes, React typically:",
             ("Re-renders the component", "Reloads the whole page",
              "Does nothing", "Mutates the original object in place"), 0),
            ("Props differ from state because props are:",
             ("Passed in from a parent and read-only to the component",
              "Always mutable internally", "Stored in localStorage", "Only numbers"), 0),
            ("Initial state for a counter starting at 0 is set with:",
             ("useState(0)", "useEffect(0)", "useRef()", "setState()"), 0),
            ("Lifting state up means:",
             ("Moving shared state to the closest common ancestor", "Storing it on window",
              "Deleting child state", "Using more refs"), 0),
            ("Derived data that can be computed from existing state:",
             ("Usually should not be stored as separate state", "Must always be its own state",
              "Should be stored in the DOM", "Cannot be computed"), 0),
            ("A controlled input gets its value from:",
             ("React state", "The DOM only", "A ref always", "localStorage"), 0),
        ],
        "intermediate": [
            ("Why is mutating state objects directly a problem?",
             ("React compares references and may skip the re-render", "It is slower to type",
              "It changes the props", "It throws a syntax error"), 0),
            ("To update one field of an object in state you should:",
             ("Create a new object with the spread operator and changed field",
              "Mutate the field and call setState()", "Edit it in the DOM", "Use a ref"), 0),
            ("React state updates inside event handlers are usually:",
             ("Batched, so multiple setStates cause one re-render", "Applied instantly and synchronously read",
              "Ignored", "Run on a worker thread"), 0),
            ("After calling setCount(count + 1) twice in one handler with the value form:",
             ("Count likely increases by 1 due to stale closure over count",
              "Count always increases by 2", "An error is thrown", "Count resets to 0"), 0),
            ("Reading state immediately after calling its setter returns:",
             ("The old value, because the update is asynchronous within the render",
              "The new value synchronously", "undefined", "a promise"), 0),
            ("To toggle a boolean in state correctly you can write:",
             ("setOpen(prev => !prev)", "setOpen(!open) only inside a loop",
              "open = !open", "useRef(!open)"), 0),
            ("Passing state down to children is done via:",
             ("Props", "Global variables", "Refs only", "The DOM"), 0),
            ("Storing the same piece of truth in two states leads to:",
             ("Synchronization bugs; prefer a single source of truth",
              "Faster rendering", "Automatic syncing by React", "A compile error"), 0),
        ],
        "advanced": [
            ("Passing a function to useState as useState(() => expensiveInit()) does what?",
             ("Computes the initial state lazily, only on the first render",
              "Runs expensiveInit on every render", "Sets state to the function itself", "Throws an error"), 0),
            ("To avoid prop drilling for deeply shared state you can use:",
             ("React Context (or a state library)", "More props at every level",
              "Refs", "Global window variables"), 0),
            ("Why can calling setState in a loop with the value form lose updates?",
             ("Each call closes over the same stale state; use the updater function instead",
              "React caps updates at one", "Loops are not allowed", "State is read-only"), 0),
            ("React's reconciliation decides what changed by:",
             ("Diffing the new element tree against the previous one",
              "Re-running the whole app", "Reading the DOM directly", "Comparing CSS"), 0),
            ("A missing or unstable key on list items can cause:",
             ("Incorrect state being preserved on the wrong item",
              "Faster rendering", "A network error", "Automatic memoization"), 0),
            ("useReducer's dispatch identity across renders is:",
             ("Stable, so it is safe to omit from effect dependencies",
              "New on every render", "Always undefined", "A promise"), 0),
            ("Putting non-serializable values (like DOM nodes) in state is discouraged because:",
             ("They do not fit React's value-based model and can cause subtle bugs",
              "They render faster", "React converts them to strings", "It is required"), 0),
            ("Concurrent features (useTransition) let you mark updates as:",
             ("Non-urgent, so React can keep the UI responsive", "Synchronous and blocking",
              "Server-only", "Disabled"), 0),
        ],
    },
    "lifecycle": {
        "basic": [
            ("The three broad phases of a React component's life are:",
             ("Mounting, updating, and unmounting", "Loading, parsing, painting",
              "Open, close, reset", "Build, test, deploy"), 0),
            ("Mounting refers to:",
             ("Inserting the component into the DOM for the first time", "Removing it from the DOM",
              "Updating its props", "Pausing it"), 0),
            ("In function components, lifecycle behavior is expressed with:",
             ("The useEffect hook", "The render method only",
              "componentDidMount only", "CSS"), 0),
            ("Unmounting is when a component is:",
             ("Removed from the DOM", "First added to the DOM",
              "Re-rendered", "Given new props"), 0),
            ("componentDidMount in a class runs:",
             ("Once, right after the component is first added to the DOM",
              "Before the first render", "On every render", "Only on unmount"), 0),
            ("A re-render (update) happens when:",
             ("State or props change", "The page is scrolled",
              "Every second automatically", "Only on reload"), 0),
            ("Cleanup logic in a function component goes in:",
             ("The function returned by useEffect", "A separate render method",
              "The component's return JSX", "A ref"), 0),
            ("The class method render() must:",
             ("Return JSX (or null) and be free of side effects",
              "Perform network requests", "Update state directly", "Mutate the DOM"), 0),
        ],
        "intermediate": [
            ("useEffect(fn, []) is the function-component equivalent of:",
             ("componentDidMount (with cleanup as componentWillUnmount)",
              "componentDidUpdate", "render", "getDerivedStateFromProps"), 0),
            ("useEffect with a dependency [count] mirrors:",
             ("componentDidUpdate filtered to when count changes",
              "componentWillMount", "render", "shouldComponentUpdate"), 0),
            ("Subscriptions set up in an effect should be removed in:",
             ("The effect's cleanup function", "componentWillMount",
              "the render body", "a ref callback"), 0),
            ("Setting state directly inside the render body causes:",
             ("An infinite render loop", "A single safe update",
              "Nothing", "A network call"), 0),
            ("The cleanup function of an effect runs:",
             ("Before the effect re-runs and on unmount", "Only on mount",
              "Only once at app start", "After every paint regardless"), 0),
            ("getDerivedStateFromProps is a:",
             ("Static method invoked before render to derive state from props",
              "Hook", "Cleanup callback", "Event handler"), 0),
            ("If an effect depends on a prop but you omit it from deps, you risk:",
             ("Using a stale value of that prop", "Too many re-renders only",
              "A compile error", "Faster rendering"), 0),
            ("Multiple useEffect calls in one component:",
             ("Run in the order they are declared", "Run in reverse order",
              "Are merged into one", "Are not allowed"), 0),
        ],
        "advanced": [
            ("Error boundaries catch render-phase errors using:",
             ("componentDidCatch / getDerivedStateFromError in a class component",
              "useEffect", "try/catch in JSX", "a global window handler only"), 0),
            ("shouldComponentUpdate / React.memo exist to:",
             ("Skip re-renders when props/state are unchanged for performance",
              "Force extra renders", "Replace useEffect", "Handle errors"), 0),
            ("In React 18 Strict Mode, mount effects may run twice in dev to:",
             ("Help detect missing cleanup and unsafe side effects",
              "Improve production speed", "Double network throughput", "Disable effects"), 0),
            ("Reading layout (e.g., element size) and synchronously re-rendering is best done in:",
             ("useLayoutEffect", "useEffect", "the render body", "a ref's constructor"), 0),
            ("An effect that updates state which is also in its own deps can cause:",
             ("An infinite update loop if not guarded", "A guaranteed single run",
              "No re-render", "A syntax error"), 0),
            ("getSnapshotBeforeUpdate lets a class component:",
             ("Capture DOM info (like scroll position) before the DOM is updated",
              "Fetch data after mount", "Replace render", "Define hooks"), 0),
            ("useEffect callbacks themselves cannot be async because:",
             ("An async function returns a promise, but effects must return a cleanup function or nothing",
              "React forbids promises", "await is not allowed in React", "It would block the main thread forever"), 0),
            ("React.memo only helps when:",
             ("Props are referentially stable between renders",
              "Props change every render", "The component has no props", "State is global"), 0),
        ],
    },
}

DATA["nodejs"] = {
    "streams": {
        "basic": [
            ("In Node.js, a Readable stream is used to:",
             ("Consume data from a source piece by piece",
              "Only write data to a file", "Replace the event loop", "Hash passwords"), 0),
            ("Which method connects a Readable stream to a Writable stream?",
             (".pipe()", ".join()", ".connect()", ".merge()"), 0),
            ("Streams are preferred over reading a whole file into memory because they:",
             ("Process data in chunks, keeping memory usage low",
              "Are always faster for tiny files", "Disable backpressure", "Avoid using buffers entirely"), 0),
            ("A Writable stream emits which event when all data has been flushed?",
             ("'finish'", "'data'", "'open'", "'readable'"), 0),
            ("fs.createReadStream returns what kind of stream?",
             ("A Readable stream", "A Writable stream", "A Duplex socket", "A plain Buffer"), 0),
            ("The 'data' event on a Readable stream delivers:",
             ("A chunk of the stream's contents", "The entire file at once",
              "Only the file size", "A close code"), 0),
            ("Which stream type is both readable and writable?",
             ("Duplex", "Readable", "Writable", "Passive"), 0),
            ("Calling .pipe() automatically handles:",
             ("Backpressure between source and destination",
              "Database transactions", "JWT verification", "DNS resolution"), 0),
        ],
        "intermediate": [
            ("Backpressure in streams refers to:",
             ("A slow consumer signaling a fast producer to pause",
              "A memory leak in the event loop", "Compression of chunks", "Encryption of data"), 0),
            ("A Transform stream is a Duplex stream that:",
             ("Modifies or transforms data as it passes through",
              "Can only read", "Can only write", "Never emits events"), 0),
            ("In object mode, a stream's chunks are:",
             ("Arbitrary JavaScript objects rather than Buffers/strings",
              "Always JSON strings", "Limited to 16 KB", "Disabled"), 0),
            ("highWaterMark configures:",
             ("The internal buffer size threshold that triggers backpressure",
              "The max number of streams", "The TLS version", "The number of CPU cores"), 0),
            ("When piping, an error on the source stream:",
             ("Is not automatically forwarded to the destination; you must handle it",
              "Always crashes Node silently", "Is ignored entirely", "Closes the process"), 0),
            ("stream.pipeline() is preferred over .pipe() chains because it:",
             ("Propagates errors and cleans up all streams on failure",
              "Is synchronous", "Skips backpressure", "Avoids callbacks entirely"), 0),
            ("Reading with stream.read(0) is sometimes used to:",
             ("Trigger the 'readable' event without consuming data",
              "Delete the stream", "Flush to disk", "Reset the highWaterMark"), 0),
            ("Pausing a flowing Readable stream is done with:",
             (".pause()", ".stop()", ".halt()", ".end()"), 0),
        ],
        "advanced": [
            ("A custom Readable implements which method to supply data?",
             ("_read(size)", "_consume()", "_emit()", "read_data()"), 0),
            ("To correctly signal end-of-data from a custom Readable you:",
             ("push(null)", "return false", "throw EOF", "call end()"), 0),
            ("A Transform stream implements _transform(chunk, enc, cb); calling cb(err) will:",
             ("Emit an 'error' and destroy the stream",
              "Silently skip the chunk", "Pause the pipeline forever", "Restart the stream"), 0),
            ("If _read pushes data faster than consumed, the internal buffer:",
             ("Grows until highWaterMark, then push() returns false to signal a pause",
              "Is discarded immediately", "Crashes the process", "Switches to object mode"), 0),
            ("Mixing 'data' listeners with async/await on the same stream risks:",
             ("Losing chunks because adding a 'data' listener switches to flowing mode",
              "A syntax error", "Doubling memory", "Disabling pipe"), 0),
            ("stream.finished(stream, cb) is used to:",
             ("Get notified when a stream is no longer readable/writable, including on error",
              "Force-close all sockets", "Compress remaining data", "Reset backpressure"), 0),
            ("A Duplex stream's readable and writable sides are:",
             ("Independent, each with its own buffer and state",
              "Always identical", "Shared one buffer", "Mutually exclusive"), 0),
            ("Async iteration (for await...of) over a Readable stream:",
             ("Consumes chunks sequentially and respects backpressure",
              "Reads the whole file into memory first", "Ignores errors", "Requires object mode"), 0),
        ],
    },
    "events": {
        "basic": [
            ("Node's EventEmitter lets objects:",
             ("Emit named events and register listeners for them",
              "Open TCP sockets only", "Read files synchronously", "Parse JSON"), 0),
            ("Which method registers a listener for an event?",
             (".on(name, fn)", ".fire(name)", ".listen(name)", ".bind(name)"), 0),
            ("To emit an event you call:",
             (".emit(name, ...args)", ".trigger(name)", ".send(name)", ".dispatch(name)"), 0),
            (".once(name, fn) registers a listener that:",
             ("Runs at most one time, then is removed", "Runs forever",
              "Runs only on error", "Runs synchronously before emit"), 0),
            ("Removing a specific listener uses:",
             (".off(name, fn) / .removeListener(name, fn)", ".delete(fn)",
              ".clear(name)", ".unbind()"), 0),
            ("Listeners for the same event are called:",
             ("Synchronously, in the order they were registered",
              "In random order", "On the next tick only", "In reverse order"), 0),
            ("Many core Node objects (streams, servers) inherit from:",
             ("EventEmitter", "Buffer", "Promise", "Array"), 0),
            ("emitter.emit returns:",
             ("true if the event had listeners, false otherwise",
              "the listener count", "always undefined", "the event name"), 0),
        ],
        "intermediate": [
            ("An EventEmitter that emits 'error' with no listener will:",
             ("Throw and typically crash the process",
              "Silently ignore it", "Retry automatically", "Log a warning only"), 0),
            ("The default max listeners warning fires after:",
             ("More than 10 listeners are added for one event",
              "100 listeners", "1 listener", "Any error"), 0),
            ("setMaxListeners(n) is used to:",
             ("Adjust the threshold before the memory-leak warning",
              "Cap total events", "Delete listeners", "Throttle emit"), 0),
            ("Passing data to listeners is done by:",
             ("Providing extra arguments to emit()", "Returning from on()",
              "Setting emitter.data", "Throwing the data"), 0),
            ("prependListener differs from on by:",
             ("Adding the listener to the front of the queue",
              "Running it once", "Running it async", "Removing others"), 0),
            ("emitter.listeners(name) returns:",
             ("A copy of the array of listeners for that event",
              "The number of listeners", "The last emitted value", "A boolean"), 0),
            ("Emitting is synchronous, which means a long listener will:",
             ("Block the event loop until it returns",
              "Run on a worker thread", "Be queued for next tick", "Be skipped"), 0),
            ("To run listener logic asynchronously you typically:",
             ("Defer work with setImmediate/queueMicrotask inside the listener",
              "Mark the event async", "Use .onAsync()", "Return a promise from emit"), 0),
        ],
        "advanced": [
            ("events.once(emitter, name) returns a promise that:",
             ("Resolves with the event args, or rejects on 'error'",
              "Never rejects", "Resolves immediately", "Resolves with listener count"), 0),
            ("events.on(emitter, name) yields an async iterator that:",
             ("Lets you for-await over emitted events",
              "Removes all listeners", "Emits synchronously", "Returns a Buffer"), 0),
            ("Capturing rejections from async listeners requires:",
             ("The captureRejections option / Symbol.for('nodejs.rejection')",
              "try/catch around emit", "Nothing; it is automatic", "A domain"), 0),
            ("A common memory leak with EventEmitters comes from:",
             ("Registering listeners repeatedly without removing them",
              "Using .once()", "Emitting too fast", "Small payloads"), 0),
            ("emit() being synchronous means errors thrown in a listener:",
             ("Propagate synchronously out of the emit() call",
              "Are caught by Node automatically", "Become unhandled rejections", "Are queued"), 0),
            ("To guarantee a listener sees only the first of many rapid emits, use:",
             (".once() plus your own debouncing/guard",
              ".on() alone", "setMaxListeners(1)", "prependListener"), 0),
            ("newListener is a special event emitted:",
             ("Before a listener is added, allowing introspection",
              "After every emit", "Only on error", "When the process exits"), 0),
            ("Wrapping an EventEmitter API as a promise is best done with:",
             ("events.once for one-shot events to avoid leaks",
              "an infinite .on loop", "polling", "process.nextTick"), 0),
        ],
    },
    "modules": {
        "basic": [
            ("In CommonJS, you export values by assigning to:",
             ("module.exports", "export default", "window.exports", "global.module"), 0),
            ("You import a CommonJS module with:",
             ("require('name')", "import name", "include('name')", "load('name')"), 0),
            ("An ES module imports with:",
             ("import x from 'name'", "require('name')", "using x", "load x"), 0),
            ("A file is treated as an ES module when:",
             ("It has .mjs extension or package.json has \"type\":\"module\"",
              "It contains a class", "It uses async", "It imports fs"), 0),
            ("require caches a module so that:",
             ("Repeated requires return the same cached exports",
              "Each require re-runs the file", "It reloads on change", "It clears memory"), 0),
            ("The built-in HTTP module is imported with:",
             ("require('http') or import http from 'node:http'",
              "require('server')", "import web", "load('http')"), 0),
            ("__dirname in CommonJS holds:",
             ("The directory path of the current module",
              "The file's contents", "The process id", "The home directory"), 0),
            ("package.json's \"main\" field specifies:",
             ("The package's entry point file", "The license",
              "The test command", "The Node version"), 0),
        ],
        "intermediate": [
            ("ES modules are loaded:",
             ("Asynchronously and are statically analyzable",
              "Synchronously like require", "Only at runtime via eval", "Never cached"), 0),
            ("__dirname and __filename are not defined in ES modules; instead use:",
             ("import.meta.url (with fileURLToPath)",
              "process.dirname", "global.__dirname", "require.main"), 0),
            ("The \"exports\" field in package.json lets you:",
             ("Define and restrict a package's public entry points",
              "List dependencies", "Set the license", "Enable TypeScript"), 0),
            ("A circular require in CommonJS returns:",
             ("A partially-populated exports object for the unfinished module",
              "undefined always", "an error", "the full module regardless"), 0),
            ("Top-level await is allowed in:",
             ("ES modules", "CommonJS modules", "JSON files", "any function"), 0),
            ("Importing a CommonJS module from an ES module gives you:",
             ("Its module.exports as the default export",
              "Named exports only", "Nothing", "A promise of the file"), 0),
            ("Conditional exports (\"import\" vs \"require\") let a package:",
             ("Ship different files for ESM and CJS consumers",
              "Encrypt its source", "Skip dependencies", "Run tests"), 0),
            ("Dynamic import() returns:",
             ("A promise that resolves to the module namespace",
              "The default export synchronously", "undefined", "a require cache key"), 0),
        ],
        "advanced": [
            ("ESM bindings are live, meaning an imported value:",
             ("Reflects later reassignments in the exporting module",
              "Is a frozen copy", "Cannot be read twice", "Is always undefined"), 0),
            ("CommonJS exports are copied by value/reference at require time, so reassigning module.exports later:",
             ("Is not seen by code that already required the module",
              "Updates all importers live", "Throws", "Clears the cache"), 0),
            ("The ESM resolution algorithm differs from CJS in that it:",
             ("Requires explicit file extensions and does not do index.js magic by default",
              "Ignores package.json", "Always uses .js", "Skips node_modules"), 0),
            ("To clear a cached CommonJS module you:",
             ("delete require.cache[require.resolve('name')]",
              "call require.reload()", "set module.fresh = true", "restart V8"), 0),
            ("Loading ESM is split into phases; the linking phase:",
             ("Resolves and wires up all imports before evaluation",
              "Runs the top-level code", "Caches to disk", "Minifies the module"), 0),
            ("import assertions / attributes (e.g. with { type: 'json' }) are used to:",
             ("Tell the loader how to interpret a non-JS module",
              "Encrypt imports", "Skip caching", "Enable await"), 0),
            ("A dual package can suffer the 'dual package hazard' when:",
             ("ESM and CJS copies of the same package hold separate state",
              "It has no main field", "It uses TypeScript", "It lacks tests"), 0),
            ("Custom ESM loaders (module.register / loader hooks) let you:",
             ("Intercept resolution and transform source before evaluation",
              "Bypass the event loop", "Disable require", "Compile to native"), 0),
        ],
    },
}

DATA["python"] = {
    "decorators": {
        "basic": [
            ("A decorator in Python is fundamentally:",
             ("A callable that takes a function and returns a function",
              "A type of loop", "A class attribute", "A comment directive"), 0),
            ("The @ syntax above a function definition is:",
             ("Syntactic sugar for func = decorator(func)",
              "A type annotation", "A docstring", "An import"), 0),
            ("Decorators are commonly used to:",
             ("Add behavior like logging or timing around a function",
              "Delete functions", "Rename modules", "Parse JSON"), 0),
            ("@staticmethod turns a method into one that:",
             ("Receives no implicit self or cls argument",
              "Always returns None", "Runs on import", "Caches results"), 0),
            ("@property lets you:",
             ("Access a method like an attribute",
              "Make a class abstract", "Freeze an object", "Add type hints"), 0),
            ("@classmethod's first parameter is conventionally:",
             ("cls, the class itself", "self", "this", "obj"), 0),
            ("Stacking two decorators @a @b on f means:",
             ("f = a(b(f))", "f = b(a(f))", "f runs twice", "a and b merge"), 0),
            ("A decorator must ultimately return:",
             ("Something callable to replace the original",
              "None", "A string", "The class"), 0),
        ],
        "intermediate": [
            ("functools.wraps is used in a decorator to:",
             ("Preserve the wrapped function's name, docstring, and metadata",
              "Make it run faster", "Cache its result", "Convert it to a class"), 0),
            ("To write a decorator that accepts arguments you:",
             ("Add an extra outer function layer that returns the decorator",
              "Use @ twice", "Pass them to wraps", "Make it a class only"), 0),
            ("functools.lru_cache memoizes a function based on:",
             ("Its arguments (which must be hashable)",
              "Its return type", "Its name", "The current time"), 0),
            ("A class can act as a decorator if it implements:",
             ("__call__", "__init__ only", "__repr__", "__enter__"), 0),
            ("Without functools.wraps, the decorated function's __name__ becomes:",
             ("The name of the inner wrapper function",
              "Unchanged", "None", "An error"), 0),
            ("Decorators are applied:",
             ("At function definition time, once",
              "On every call", "Only when imported twice", "At interpreter exit"), 0),
            ("@functools.cached_property differs from @property by:",
             ("Computing once and caching the value on the instance",
              "Recomputing every access", "Being class-level", "Requiring args"), 0),
            ("To preserve correct introspection, a decorator should:",
             ("Forward *args and **kwargs to the wrapped function",
              "Hard-code two parameters", "Ignore arguments", "Return a string"), 0),
        ],
        "advanced": [
            ("A parameterized decorator @deco(x) evaluates by:",
             ("Calling deco(x) first, then applying its return value to the function",
              "Applying deco directly to x", "Running the function twice", "Ignoring x"), 0),
            ("lru_cache(maxsize=None) provides:",
             ("An unbounded cache that never evicts entries",
              "A cache of size 1", "No caching", "A weak cache"), 0),
            ("A decorator implemented as a class storing state across calls works because:",
             ("The instance persists and __call__ runs per invocation",
              "Classes cannot hold state", "Python re-instantiates each call", "It uses globals"), 0),
            ("Decorating a method inside a class with a plain function decorator means the wrapper:",
             ("Receives self as its first positional argument",
              "Loses access to self", "Becomes static automatically", "Cannot be called"), 0),
            ("functools.singledispatch enables:",
             ("Function overloading based on the first argument's type",
              "Multithreading", "Caching by name", "Lazy imports"), 0),
            ("A decorator that returns a different callable each call would break:",
             ("Identity/memoization assumptions; it should usually return one stable wrapper",
              "Nothing", "Only async code", "The import system"), 0),
            ("To make lru_cache work on a method without leaking instances, prefer:",
             ("cached_property or caching keyed off hashable args, avoiding self leaks",
              "lru_cache directly on the method always", "global dicts", "no caching ever"), 0),
            ("Class decorators receive and return:",
             ("The class object, allowing it to be modified or replaced",
              "An instance", "A metaclass only", "None"), 0),
        ],
    },
    "generators": {
        "basic": [
            ("A generator function is defined using:",
             ("yield inside a function", "return only", "async def", "@generator"), 0),
            ("Calling a generator function returns:",
             ("A generator object (an iterator)", "The first value",
              "A list", "None"), 0),
            ("yield differs from return because it:",
             ("Pauses the function and resumes later, preserving state",
              "Ends the function permanently", "Raises an error", "Returns a list"), 0),
            ("You advance a generator with:",
             ("next(gen)", "gen.run()", "gen.step()", "call(gen)"), 0),
            ("Generators are mainly used to:",
             ("Produce values lazily, one at a time",
              "Sort lists", "Open files", "Define classes"), 0),
            ("A generator expression looks like:",
             ("(x*x for x in range(10))", "[x*x for x in range(10)]",
              "{x*x for x in range(10)}", "lambda x: x*x"), 0),
            ("When a generator has no more values, next() raises:",
             ("StopIteration", "IndexError", "ValueError", "EOFError"), 0),
            ("A key memory advantage of generators is that they:",
             ("Do not build the whole sequence in memory at once",
              "Always run faster", "Use multiple cores", "Cache all values"), 0),
        ],
        "intermediate": [
            ("yield from is used to:",
             ("Delegate iteration to a sub-iterator/sub-generator",
              "Return early", "Catch exceptions", "Define a coroutine"), 0),
            ("gen.send(value) does what?",
             ("Resumes the generator, making the paused yield evaluate to value",
              "Sends an email", "Restarts the generator", "Closes it"), 0),
            ("A generator's return value (PEP 380) is delivered via:",
             ("The StopIteration exception's value attribute",
              "next()'s return", "a global", "yield"), 0),
            ("gen.close() raises inside the generator:",
             ("GeneratorExit at the paused yield",
              "StopIteration", "KeyError", "nothing"), 0),
            ("Generators are lazy, so an infinite generator is fine as long as you:",
             ("Consume only a finite prefix of it",
              "Call list() on it", "Sort it", "Reverse it"), 0),
            ("itertools is useful with generators because it provides:",
             ("Lazy building blocks like islice, chain, and count",
              "GUI widgets", "HTTP servers", "JSON parsing"), 0),
            ("Iterating a generator a second time yields:",
             ("Nothing; it is already exhausted",
              "The same values again", "An error", "Reversed values"), 0),
            ("yield from sub also forwards:",
             ("send() and throw() to the delegated generator",
              "Only the first value", "Exceptions only", "Nothing"), 0),
        ],
        "advanced": [
            ("gen.throw(Exc) does what?",
             ("Raises Exc at the point where the generator is paused",
              "Returns Exc", "Closes silently", "Restarts the generator"), 0),
            ("A generator used as a coroutine (pre-async) could:",
             ("Receive values via send and produce via yield, two-way",
              "Only produce values", "Run on threads", "Not be paused"), 0),
            ("yield from g returns to the delegating generator:",
             ("The value of StopIteration raised by g",
              "g's last yield", "None always", "a list of g's values"), 0),
            ("Wrapping a generator in contextlib.contextmanager makes yield:",
             ("Split setup (before yield) and teardown (after yield) for a with-block",
              "Return a file", "Run async", "Disable StopIteration"), 0),
            ("If a GeneratorExit is caught and the generator yields again, Python:",
             ("Raises RuntimeError because it must not yield during close",
              "Restarts it", "Ignores it", "Returns None"), 0),
            ("Generator state (local variables) is stored:",
             ("On the generator object's frame, persisting between next() calls",
              "In globals", "On the stack only during a call", "In a cache file"), 0),
            ("Chaining generators (pipelines) is efficient because each stage:",
             ("Pulls one item at a time on demand, keeping memory flat",
              "Materializes a full list", "Runs in parallel threads", "Caches everything"), 0),
            ("A subtle bug with generators in a loop closure is that:",
             ("Late binding means they may all see the final loop variable value",
              "They cannot be nested", "They ignore yield", "They run eagerly"), 0),
        ],
    },
    "async": {
        "basic": [
            ("An async function is declared with:",
             ("async def", "def async", "@async", "function*"), 0),
            ("Calling an async function returns:",
             ("A coroutine object", "Its result directly", "A thread", "None"), 0),
            ("Inside an async function you wait on another coroutine with:",
             ("await", "yield", "return", "wait()"), 0),
            ("To actually run a top-level coroutine you typically use:",
             ("asyncio.run(main())", "main()", "thread.start()", "run(main)"), 0),
            ("asyncio is best suited for:",
             ("I/O-bound concurrency", "CPU-bound number crunching",
              "Replacing all threads", "Compiling code"), 0),
            ("await can only be used:",
             ("Inside an async function", "Anywhere", "In class bodies", "In list comprehensions only"), 0),
            ("An event loop in asyncio is responsible for:",
             ("Scheduling and running coroutines and callbacks",
              "Garbage collection", "Parsing source", "Type checking"), 0),
            ("asyncio.sleep(1) differs from time.sleep(1) because it:",
             ("Yields control to the event loop instead of blocking the thread",
              "Sleeps twice as long", "Blocks all coroutines", "Is synchronous"), 0),
        ],
        "intermediate": [
            ("asyncio.gather is used to:",
             ("Run multiple awaitables concurrently and collect their results",
              "Run them strictly in sequence", "Cancel all tasks", "Create threads"), 0),
            ("asyncio.create_task schedules a coroutine to:",
             ("Run concurrently on the event loop right away",
              "Run only when awaited", "Run on a new process", "Block the loop"), 0),
            ("A blocking (synchronous) call inside a coroutine will:",
             ("Stall the entire event loop until it returns",
              "Run on another core automatically", "Be skipped", "Raise immediately"), 0),
            ("To run blocking code without stalling the loop, use:",
             ("asyncio.to_thread / run_in_executor",
              "time.sleep", "a bare await", "gather"), 0),
            ("Awaiting a coroutine vs awaiting a Task differs in that a Task:",
             ("Is already scheduled and runs concurrently before you await it",
              "Cannot be awaited", "Runs synchronously", "Blocks creation"), 0),
            ("asyncio.gather(..., return_exceptions=True) causes exceptions to be:",
             ("Returned in the results list rather than raised immediately",
              "Ignored entirely", "Logged only", "Re-raised twice"), 0),
            ("An 'async with' statement requires the context manager to define:",
             ("__aenter__ and __aexit__", "__enter__ only",
              "__call__", "__iter__"), 0),
            ("'async for' iterates over an object implementing:",
             ("__aiter__ and __anext__", "__next__ only",
              "yield", "__getitem__"), 0),
        ],
        "advanced": [
            ("Cancelling a Task raises inside the coroutine:",
             ("asyncio.CancelledError at the current await point",
              "StopIteration", "TimeoutError", "nothing"), 0),
            ("asyncio.wait_for(coro, timeout) on timeout will:",
             ("Cancel the coroutine and raise TimeoutError",
              "Return None silently", "Block forever", "Retry automatically"), 0),
            ("A 'fire and forget' task whose reference is dropped may:",
             ("Be garbage collected and never finish; keep a reference",
              "Always complete", "Run on a thread", "Raise at creation"), 0),
            ("asyncio.TaskGroup (3.11+) improves on gather by:",
             ("Providing structured concurrency that cancels siblings on failure",
              "Running synchronously", "Disabling cancellation", "Avoiding await"), 0),
            ("Mixing two event loops (e.g., calling asyncio.run twice nested) causes:",
             ("A RuntimeError because a loop is already running",
              "Faster execution", "Silent success", "A new thread"), 0),
            ("An un-awaited coroutine triggers:",
             ("A 'coroutine was never awaited' RuntimeWarning",
              "An immediate result", "A syntax error", "A new task"), 0),
            ("Shielding a coroutine from cancellation uses:",
             ("asyncio.shield", "asyncio.protect", "task.lock()", "await guard"), 0),
            ("CPU-bound work in asyncio is best offloaded to:",
             ("A process pool via run_in_executor, since the GIL blocks threads",
              "More coroutines", "asyncio.sleep", "a tight await loop"), 0),
        ],
    },
}

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    build(os.path.join(here, "questions.data.json"))
